/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiExportDotcsvRouteImport } from './routes/api/export[.]csv'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportDotcsvRoute = ApiExportDotcsvRouteImport.update({
  id: '/api/export.csv',
  path: '/api/export.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/export.csv': typeof ApiExportDotcsvRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/export.csv': typeof ApiExportDotcsvRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/export.csv': typeof ApiExportDotcsvRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/export.csv'
    | '/api/signals'
    | '/api/telegram'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/export.csv'
    | '/api/signals'
    | '/api/telegram'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/export.csv'
    | '/api/signals'
    | '/api/telegram'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiExportDotcsvRoute: typeof ApiExportDotcsvRoute
  ApiSignalsRoute: typeof ApiSignalsRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export.csv': {
      id: '/api/export.csv'
      path: '/api/export.csv'
      fullPath: '/api/export.csv'
      preLoaderRoute: typeof ApiExportDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiExportDotcsvRoute: ApiExportDotcsvRoute,
  ApiSignalsRoute: ApiSignalsRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
